Armbian 9tripod / Indienova patchset
armbian/linux-rockchip pull request #11
Opened 2023-03-22 05:18 UTC by stvhay

2023-03-22 13:07 UTC, amazingfate requested changes

2023-03-22 13:07 UTC, amazingfate commented on arch/arm64/boot/dts/rockchip/rk3588-linux.dtsi
I don't want to change this file because it's from the upstream SDK. You can delete this node in the board dts like other board: https://github.com/armbian/linux-rockchip/blob/rockchip-5.10/arch/arm64/boot/dts/rockchip/rk3588-rock-5b.dts#L29

2023-03-22 13:07 UTC, amazingfate commented on arch/arm64/boot/dts/rockchip/rk3588s.dtsi
This is not a board level change and will affect other boards. You can move this to another pr so that we can discuess this change there.

2023-03-22 13:07 UTC, amazingfate commented on drivers/net/wireless/rockchip_wlan/rtl8821cs/core/monitor/rtw_radiotap.c
There are many changes like this, I don't think it is necessary.

2023-03-22 17:04 UTC, stvhay commented on arch/arm64/boot/dts/rockchip/rk3588-linux.dtsi
That's reasonable to me

2023-03-22 17:06 UTC, stvhay commented on arch/arm64/boot/dts/rockchip/rk3588s.dtsi
Sure

2023-03-22 17:08 UTC, stvhay commented on drivers/net/wireless/rockchip_wlan/rtl8821cs/core/monitor/rtw_radiotap.c
This commit replaces an older version of the driver with newer version. Wouldn't we want to sync with that version vs creating a third custom version of the code where possible?

2023-04-08 12:29 UTC, rpardini commented
This `rockchip_wlan` driver stuff is puzzling.

2023-04-14 11:55 UTC, rpardini commented on arch/arm64/boot/dts/rockchip/rk3588-linux.dtsi
I had the same on the Mekotronics. Using the trick amazingfate mentions (delete the node at the board DTS) works.

2023-04-14 11:56 UTC, rpardini commented on arch/arm64/boot/dts/rockchip/rk3588s.dtsi
Agreed, no changing the common dtsi is needed.

2023-06-05 08:35 UTC, closed without merging