use 'python3', not 'python'
armbian/linux-rockchip pull request #13
Opened 2023-04-03 19:33 UTC by rpardini

This fixes the installation of the `linux-headers` package for this kernel.

Half of this kernel depends on `python3` already but the other half doesn't.

I tried other ways to solve this (eg: injecting a `python` symlink at the PATH when building linux-headers; adding dependency for python-is-python3; etc) but they all end up failing in one stage or another. Not all Debian/Ubuntu releases have `python2` either, and `python-is-python3` is not common across all releases. So, here we are.

2023-04-04 04:32 UTC, amazingfate commented
But why mainline is still using python?
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/networking/device_drivers/atm/cxacru-cf.py?h=v6.3-rc5

2023-04-04 04:43 UTC, amazingfate commented
Here is one commit I find upstream dropping python2 support: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/?h=v6.3-rc5&id=4217e5074f33d855873370378d427e329b60a7b4

2023-04-04 05:11 UTC, amazingfate requested changes

2023-04-04 05:11 UTC, amazingfate commented on Documentation/networking/device_drivers/atm/cxacru-cf.py
This file is the same with the upstream one. Keeping it unchanged should be safe.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/Documentation/networking/device_drivers/atm/cxacru-cf.py?h=v6.3-rc5

2023-04-04 05:11 UTC, amazingfate commented on Documentation/sphinx/maintainers_include.py
Find one upstream commit editing this file to drop python2: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/?h=v6.3-rc5&id=4217e5074f33d855873370378d427e329b60a7b4

2023-04-04 05:11 UTC, amazingfate commented on Documentation/target/tcm_mod_builder.py
This file is the same with the upstream one: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/Documentation/target/tcm_mod_builder.py?h=v6.3-rc5

2023-04-04 05:11 UTC, amazingfate commented on Documentation/trace/postprocess/decode_msr.py
This file is the same with the upstream one: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/Documentation/trace/postprocess/decode_msr.py?h=v6.3-rc5

2023-04-04 05:11 UTC, amazingfate commented on arch/ia64/scripts/unwcheck.py
Find one upstream commit: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/?h=v6.3-rc5&id=d8d2d38275c1b2d3936c0d809e0559e88912fbb5

2023-04-04 05:11 UTC, amazingfate commented on drivers/staging/greybus/tools/lbtest
This file is the same with the upstream one: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/drivers/staging/greybus/tools/lbtest?h=v6.3-rc5

2023-04-04 05:11 UTC, amazingfate commented on scripts/bmpconvert
This file is added by rockchip, seems good to change.

2023-04-04 05:11 UTC, amazingfate commented on scripts/clang-wrapper.py
This file is added by rockchip, seems good to change.

2023-04-04 05:11 UTC, amazingfate commented on scripts/gcc-wrapper.py
This file is added by rockchip, seems good to change.

2023-04-04 05:11 UTC, amazingfate commented on scripts/jobserver-exec
Find one upstream commit: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/?h=v6.3-rc5&id=d8d2d38275c1b2d3936c0d809e0559e88912fbb5

2023-04-04 05:11 UTC, amazingfate commented on scripts/mkbootimg
This file is added by rockchip, seems good to change.

2023-04-04 05:11 UTC, amazingfate commented on scripts/mkmultidtb.py
This file is added by rockchip, seems good to change.

2023-04-04 05:11 UTC, amazingfate commented on scripts/show_delta
This file is the same with the upstream one: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/scripts/show_delta?h=v6.3-rc5

2023-04-04 05:11 UTC, amazingfate commented on scripts/spdxcheck.py
Find one upstream commit doing the same: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/?h=v6.3-rc5&id=d0259c42abff51b586496a0594933e394efefbc5

2023-04-04 05:11 UTC, amazingfate commented on scripts/tracing/draw_functrace.py
Upstream is still using python: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/tracing/draw_functrace.py?h=v6.3-rc5

2023-04-04 05:11 UTC, amazingfate commented on scripts/unpack_bootimg
This file is added by rockchip, seems good to change.

2023-04-04 05:11 UTC, amazingfate commented on tools/hv/lsvmbus
This file is the same with upstream: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/tools/hv/lsvmbus?h=v6.3-rc5

2023-04-04 05:11 UTC, amazingfate commented on tools/perf/python/tracepoint.py
Find one upstream commit: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/diff/?h=v6.3-rc5&id=7e2022af7921978ce37bb8fc1a35239b81cbc1af

2023-04-04 05:11 UTC, amazingfate commented on tools/perf/python/twatch.py
This file is the same with the upstream one: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/tools/perf/python/twatch.py?h=v6.3-rc5

2023-04-04 05:11 UTC, amazingfate commented on tools/perf/scripts/python/exported-sql-viewer.py
Upstream is still using python: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/scripts/python/exported-sql-viewer.py?h=v6.3-rc5

2023-04-04 05:11 UTC, amazingfate commented on tools/power/x86/intel_pstate_tracer/intel_pstate_tracer.py
Upstream is still using python: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/power/x86/intel_pstate_tracer/intel_pstate_tracer.py?h=v6.3-rc5

2023-04-04 05:11 UTC, amazingfate commented on tools/testing/selftests/drivers/net/mlxsw/sharedbuffer_configuration.py
This file is the same with the upstream one: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/log/tools/testing/selftests/drivers/net/mlxsw/sharedbuffer_configuration.py?h=v6.3-rc5

2023-04-08 20:01 UTC, rpardini commented on tools/power/x86/intel_pstate_tracer/intel_pstate_tracer.py
Sent fixup reverting this change.

2023-04-08 20:01 UTC, rpardini commented on tools/perf/scripts/python/exported-sql-viewer.py
Sent fixup reverting this change.

2023-04-08 20:01 UTC, rpardini commented on scripts/tracing/draw_functrace.py
Sent fixup reverting this change.

2023-04-14 07:31 UTC, amazingfate requested changes

2023-04-14 07:31 UTC, amazingfate commented on Documentation/target/tcm_mod_builder.py
Is this change necessary? Upstream is still using python.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/target/tcm_mod_builder.py?h=v6.3-rc6#n1

2023-04-14 07:31 UTC, amazingfate commented on Documentation/trace/postprocess/decode_msr.py
Is this change necessary? Upstream is still using python.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/trace/postprocess/decode_msr.py?h=v6.3-rc6#n1

2023-04-14 07:31 UTC, amazingfate commented on drivers/staging/greybus/tools/lbtest
Is this change necessary? Upstream is still using python.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/staging/greybus/tools/lbtest?h=v6.3-rc6

2023-04-14 07:31 UTC, amazingfate commented on scripts/show_delta
Is this change necessary? Upstream is still using python.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/show_delta?h=v6.3-rc6

2023-04-14 07:31 UTC, amazingfate commented on tools/hv/lsvmbus
Is this change necessary? Upstream is still using python.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/hv/lsvmbus?h=v6.3-rc6

2023-04-14 07:31 UTC, amazingfate commented on tools/perf/python/twatch.py
Is this change necessary? Upstream is still using python.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/python/twatch.py?h=v6.3-rc6

2023-04-14 07:31 UTC, amazingfate commented on tools/testing/selftests/drivers/net/mlxsw/sharedbuffer_configuration.py
Is this change necessary? Upstream is still using python.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/testing/selftests/drivers/net/mlxsw/sharedbuffer_configuration.py?h=v6.3-rc6

2023-04-14 11:44 UTC, rpardini commented
Ok, I've removed all the ones @amazingfate  mentioned, and force-pushed a single squashed commit with only the ones that remained.
This is enough to build and install the `linux-headers` on `bookworm` (which doesnt have python2).
The resulting headers are enough to make `v4l2loopback-dkms` install build and work correctly.
Proof: https://github.com/rpardini/armbian-release/actions/runs/4699266074/jobs/8332553849#step:4:655

2023-04-14 12:29 UTC, amazingfate approved these changes

2023-04-14 20:50 UTC, merged