media: rockchip: hdmirx: add VIDIOC_S_PARM and VIDIOC_G_PARM
armbian/linux-rockchip pull request #139
Opened 2024-01-08 02:35 UTC by amazingfate

This will let obs linux-v4l2 plugin show display from hdmirx of rk3588.
OBS code using these API: https://github.com/obsproject/obs-studio/blob/master/plugins/linux-v4l2/v4l2-helpers.c#L244-L254

@ramiropolla @rigaya

2024-01-08 10:11 UTC, ramiropolla requested changes
I'm not a kernel dev, but after a quick glance and checking how other drivers do it, I see at least two issues:
- hdmirx_g_parm() is not checking for parm->type like other drivers
- if changing parameters is not supported, then we shouldn't implement vidioc_s_parm() (although I see there's a function called hdmirx_s_dv_timings())
- I'm not sure about the readbuffers. where did you get that info?

2024-01-11 09:23 UTC, amazingfate commented
I don't know readbuffers value exactly, it just works. Maybe not returning it will work, I will test.
I will add check for type `V4L2_BUF_TYPE_VIDEO_CAPTURE` and remove vidioc_s_parm to see if it will work.

2024-01-12 12:29 UTC, amazingfate commented
Add checking `parm->type` is `V4L2_BUF_TYPE_VIDEO_CAPTURE_MPLANE`, remove `vidioc_s_parm` and return of `readbuffers`.
Tested on obs with mesa llvmpipe driver, panfork driver failed with gl call error.

2024-04-27 01:30 UTC, amazingfate commented
This commit is not that useful on 5.10 kernel because GPU support is bad. Since we have panthor support on 6.1, I will test with panthor and create a pr for 6.1 kernel.

2024-04-27 01:30 UTC, closed without merging