Patch 6
armbian/linux-rockchip pull request #40
Opened 2023-06-06 13:29 UTC by Joshua-Riek

The Orange Pi 5B eMMC conflicts with the SPI flash on the Orange Pi 5. So I propose adding the Orange Pi 5B device tree again to allow the eMMC to be used.

2023-06-06 14:30 UTC, efectn reviewed
What about to include 5's devicetree and make the needed changes? Seems cleaner to me

2023-06-06 14:40 UTC, Joshua-Riek commented
That is a good idea since they are so similar. I'll work on the change later today.

2023-06-06 17:08 UTC, Joshua-Riek commented
Changes pushed, looks so much cleaner now.

2023-06-06 17:14 UTC, efectn commented
> Changes pushed, looks so much cleaner now.

Can you also disable sdhci node from arch/arm64/boot/dts/rockchip/rk3588s-orangepi.dtsi and enable it on 5b's tree

2023-06-06 17:36 UTC, efectn approved these changes, later dismissed

2023-06-07 05:24 UTC, amazingfate requested changes

2023-06-07 05:24 UTC, amazingfate commented on arch/arm64/boot/dts/rockchip/rk3588s-orangepi-5b.dts
> +}
```
Error: arch/arm64/boot/dts/rockchip/rk3588s-orangepi-5b.dts:20.1-5 syntax error

[🐳|🔨]   FATAL ERROR: Unable to parse input tree
```
Missing `;`

2023-06-07 12:40 UTC, Joshua-Riek commented on arch/arm64/boot/dts/rockchip/rk3588s-orangepi-5b.dts
> +}
Fixed!

2023-06-07 14:54 UTC, amazingfate approved these changes

2023-06-07 14:55 UTC, merged